### ISSUE TITLE
is the timezone included in DateTimeValueType

### ISSUE THREAD

**Issue by Joerg-Schoemer** [Beschaffungsamt/pracc-esens#14]
rim:DateTimeValueType has a value element of type xs:dateTime see https://www.w3schools.com/xml/schema_dtypes_date.asp

**Comment by Joerg-Schoemer** [comment]
A schematron rule will be created to ensure the presence of the timezone

**Comment by f-tsakonas** [comment]
Schematron rule implemented in schematrons for transactions 011 and 012
