### ISSUE TITLE
Rules for Tendering Answers 

### ISSUE THREAD

**Issue by Joerg-Schoemer** [Beschaffungsamt/pracc-esens#4]
Broadcast of Tendering Answers to all subscribed EOs should be foreseen. The Tendering Answers should be included as attachments to the Call for Tenders so “late comers” are able to read them, too.

**Comment by mondorf** [comment]
A guideline will be included to the PEPPOL BIS "Call for Tender Questions and Answers" and the BPMN models will be updated to clarify the following apsects in the specifications:
- Tendering Answers have to be sent to all EOs
- The Tendering Answers shall not contain any indentification details of the Economic Operators that issued questions
- The Call for Tender has to be updated and resend to all subsribed EOs after the issuing of answers by the CA.

**Comment by mondorf** [comment]
The corresponding behaviour was clarified in the Profile and in the Process Description and in the Transaction Description.
