### ISSUE TITLE
Include BuyerPartyIdentification and Notice Version in Search Notice?!

### ISSUE THREAD

**Issue by f-tsakonas** [Beschaffungsamt/pracc-esens#42]
tbd -> include slots into search notice like in the publish notice?

**Comment by mondorf** [comment]
eForms Version is included in syntax mapping but must be included to the Data model. eForms Version is included twice in Example of Search Notice Response

**Comment by mondorf** [comment]
The Value of eFormVersion has a new format indicated by the eFORMS specifications. The difference is that -sdk- is introduced in between bersion and eforms. Please check section 4.1.2. Versioning https://docs.ted.europa.eu/eforms/0.3.0/index.html#elementsSection

I have updated the example.

Could you amend the corresponding business rule: https://interplat-bmi-evergabe-lb01.test-server.ag/pracc/rules/PEPPOL-T012-R025/

**Comment by f-tsakonas** [comment]
Resolved during meeting by Ansgar

**Comment by mondorf** [comment]
SDK was included to all documents
