### ISSUE TITLE
UBL version ID

### ISSUE THREAD

**Issue by mondorf** [Beschaffungsamt/pracc-esens#6]
A proposal has been made to use UBL 2.2 instead of UBL 2.3. The reason is that the publication date of UBL is not clear yet and the namespace of UBL 2.3 might change after its official publication. It was suggested to update to UBL 2.3 later on.

**Comment by mondorf** [comment]
UBL 2.2 will be adopted

**Comment by Joerg-Schoemer** [comment]
use only UBL-Version 2.2
