### ISSUE TITLE
Naming conventions for Profile IDs and Customization IDs

### ISSUE THREAD

**Issue by mondorf** [Beschaffungsamt/pracc-esens#9]
During the PEPPOL WG meeting it was mentioned that there might be new rules how the Profile IDs and Customization IDs should be build and that these rules should be considered. 

Current IDs:

Profile IDs
urn:fdc:peppol.eu:2020:pracc:p004:01:1.0
urn:fdc:peppol.eu:2020:pracc:p005:01:1.0
urn:fdc:peppol.eu:2020:pracc:p006:01:1.0
urn:fdc:peppol.eu:2020:pracc:p007:01:1.0

CustomizationIDs
urn:www.cenbii.eu:transaction:biitrdm084:ver3.0:extended:urn:fdc:peppol.eu:2020:pracc:t007:ver1.0
urn:www.cenbii.eu:transaction:biitrdm085:ver3.0:extended:urn:fdc:peppol.eu:2020:pracc:t008:ver1.0
urn:www.cenbii.eu:transaction:biitrdm084:ver3.0:extended:urn:fdc:peppol.eu:2020:pracc:t009:ver1.0
urn:www.cenbii.eu:transaction:biitrdm085:ver3.0:extended:urn:fdc:peppol.eu:2020:pracc:t010:ver1.0
urn:www.cenbii.eu:transaction:biitrdm099:ver3.0:extended:urn:fdc:peppol.eu:2020:pracc:t011:ver1.0
urn:www.cenbii.eu:transaction:biitrdm100:ver3.0:extended:urn:fdc:peppol.eu:2020:pracc:t012:ver1.0
urn:www.cenbii.eu:transaction:biitrdm089:ver3.0:extended:urn:fdc:peppol.eu:2020:pracc:t013:ver1.0
urn:www.cenbii.eu:transaction:biitrdm045:ver3.0:extended:urn:fdc:peppol.eu:2020:pracc:t014:ver1.0

**Comment by mondorf** [comment]
The editors will identify the new rules for Customization IDs and Profile IDs and create new suggestions.

**Comment by Joerg-Schoemer** [comment]
@jerouris could you please find us the correct rules to build the "PEPPOL-IDs"

**Comment by jerouris** [comment]
Yes, I'll have a look this week.

**Comment by mondorf** [comment]
[PEPPOL PRAC release plan eTendering April 2021.xlsx](https://github.com/Beschaffungsamt/pracc-esens/files/6384172/PEPPOL.PRAC.release.plan.eTendering.April.2021.xlsx)
